#!/usr/bin/env npx ts-node

/**
 * Overnight Job Scraping Script
 * Adds verified jobs from major digital asset companies to Supabase
 */

import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY!

const supabase = createClient(supabaseUrl, supabaseKey)

interface JobInsert {
  title: string
  company: string
  company_type: string
  location: string
  type: string
  department: string | null
  salary_display: string | null
  salary_min: number | null
  salary_max: number | null
  salary_currency: string
  description: string
  requirements: string[]
  url: string
  posted_date: string
  tags: string[]
  featured: boolean
  is_remote: boolean
  country: string | null
  country_code: string | null
  city: string | null
  seniority: string | null
  work_arrangement: string
  skills: string[]
  benefits: string[]
  verified: boolean
  source: string | null
}

// New jobs scraped on 2026-03-18
const newJobs: JobInsert[] = [
  // Galaxy Digital Jobs
  {
    title: 'Executive Assistant, Asset Management',
    company: 'Galaxy Digital',
    company_type: 'Asset Management',
    location: 'New York, NY',
    type: 'Full-time',
    department: 'Admin',
    salary_display: null,
    salary_min: null,
    salary_max: null,
    salary_currency: 'USD',
    description: 'Executive Assistant supporting the Asset Management team at Galaxy Digital, one of the leading digital asset and blockchain financial services firms.',
    requirements: ['5+ years executive assistant experience', 'Financial services background', 'Excellent organizational skills'],
    url: 'https://job-boards.greenhouse.io/galaxydigitalservices/jobs/5823528004',
    posted_date: '2026-03-18',
    tags: ['admin', 'asset management', 'crypto'],
    featured: false,
    is_remote: false,
    country: 'United States',
    country_code: 'US',
    city: 'New York',
    seniority: 'Mid',
    work_arrangement: 'On-site',
    skills: ['Administration', 'Calendar Management', 'Communication'],
    benefits: ['401k', 'Health Insurance', 'Flexible PTO'],
    verified: true,
    source: 'greenhouse'
  },
  {
    title: 'Associate/VP, Capital Formation',
    company: 'Galaxy Digital',
    company_type: 'Asset Management',
    location: 'New York, NY',
    type: 'Full-time',
    department: 'Asset Management',
    salary_display: '$150,000 - $250,000',
    salary_min: 150000,
    salary_max: 250000,
    salary_currency: 'USD',
    description: 'Capital Formation role focused on investor relations and fundraising for Galaxy\'s digital asset funds.',
    requirements: ['3-7 years in capital formation', 'Institutional investor relationships', 'Digital assets knowledge'],
    url: 'https://job-boards.greenhouse.io/galaxydigitalservices/jobs/5786165004',
    posted_date: '2026-03-18',
    tags: ['capital formation', 'investor relations', 'fundraising'],
    featured: true,
    is_remote: false,
    country: 'United States',
    country_code: 'US',
    city: 'New York',
    seniority: 'Senior',
    work_arrangement: 'Hybrid',
    skills: ['Investor Relations', 'Fundraising', 'Sales', 'Digital Assets'],
    benefits: ['401k', 'Health Insurance', 'Equity', 'Flexible PTO'],
    verified: true,
    source: 'greenhouse'
  },
  {
    title: 'Senior Volatility and Options Strategist',
    company: 'Galaxy Digital',
    company_type: 'Asset Management',
    location: 'New York, NY',
    type: 'Full-time',
    department: 'Asset Management',
    salary_display: '$200,000 - $350,000',
    salary_min: 200000,
    salary_max: 350000,
    salary_currency: 'USD',
    description: 'Lead volatility and options strategy development for digital asset portfolios.',
    requirements: ['7+ years derivatives trading', 'Options pricing expertise', 'Crypto markets experience preferred'],
    url: 'https://job-boards.greenhouse.io/galaxydigitalservices/jobs/5789843004',
    posted_date: '2026-03-18',
    tags: ['trading', 'derivatives', 'options', 'quantitative'],
    featured: true,
    is_remote: false,
    country: 'United States',
    country_code: 'US',
    city: 'New York',
    seniority: 'Senior',
    work_arrangement: 'On-site',
    skills: ['Options Trading', 'Derivatives', 'Quantitative Analysis', 'Risk Management'],
    benefits: ['401k', 'Health Insurance', 'Equity', 'Performance Bonus'],
    verified: true,
    source: 'greenhouse'
  },
  {
    title: 'VP, Java Electronic Trading Developer',
    company: 'Galaxy Digital',
    company_type: 'Asset Management',
    location: 'New York, NY',
    type: 'Full-time',
    department: 'Engineering',
    salary_display: '$200,000 - $300,000',
    salary_min: 200000,
    salary_max: 300000,
    salary_currency: 'USD',
    description: 'Build and maintain low-latency electronic trading systems for digital asset markets.',
    requirements: ['7+ years Java development', 'Electronic trading systems experience', 'Low-latency optimization'],
    url: 'https://job-boards.greenhouse.io/galaxydigitalservices/jobs/5353025004',
    posted_date: '2026-03-18',
    tags: ['java', 'trading', 'engineering', 'fintech'],
    featured: false,
    is_remote: false,
    country: 'United States',
    country_code: 'US',
    city: 'New York',
    seniority: 'Senior',
    work_arrangement: 'On-site',
    skills: ['Java', 'Electronic Trading', 'Low Latency', 'Financial Systems'],
    benefits: ['401k', 'Health Insurance', 'Equity'],
    verified: true,
    source: 'greenhouse'
  },
  {
    title: 'Senior Mobile Developer | GK8 by Galaxy',
    company: 'Galaxy Digital',
    company_type: 'Custody',
    location: 'New York, NY',
    type: 'Full-time',
    department: 'Engineering',
    salary_display: '$180,000 - $250,000',
    salary_min: 180000,
    salary_max: 250000,
    salary_currency: 'USD',
    description: 'Develop mobile applications for GK8 institutional custody platform.',
    requirements: ['5+ years mobile development', 'iOS/Android expertise', 'Security-focused development'],
    url: 'https://job-boards.greenhouse.io/galaxydigitalservices/jobs/5477291004',
    posted_date: '2026-03-18',
    tags: ['mobile', 'ios', 'android', 'custody'],
    featured: false,
    is_remote: false,
    country: 'United States',
    country_code: 'US',
    city: 'New York',
    seniority: 'Senior',
    work_arrangement: 'Hybrid',
    skills: ['iOS', 'Android', 'Swift', 'Kotlin', 'Security'],
    benefits: ['401k', 'Health Insurance', 'Equity'],
    verified: true,
    source: 'greenhouse'
  },
  {
    title: 'AI & Trading Engineer',
    company: 'Galaxy Digital',
    company_type: 'Asset Management',
    location: 'New York, NY',
    type: 'Full-time',
    department: 'Engineering',
    salary_display: '$220,000 - $320,000',
    salary_min: 220000,
    salary_max: 320000,
    salary_currency: 'USD',
    description: 'Apply AI/ML techniques to trading strategies and market analysis.',
    requirements: ['5+ years ML/AI experience', 'Trading systems knowledge', 'Python and relevant frameworks'],
    url: 'https://job-boards.greenhouse.io/galaxydigitalservices/jobs/5812716004',
    posted_date: '2026-03-18',
    tags: ['ai', 'machine learning', 'trading', 'quantitative'],
    featured: true,
    is_remote: false,
    country: 'United States',
    country_code: 'US',
    city: 'New York',
    seniority: 'Senior',
    work_arrangement: 'Hybrid',
    skills: ['Python', 'Machine Learning', 'AI', 'Trading', 'Quantitative Analysis'],
    benefits: ['401k', 'Health Insurance', 'Equity', 'Performance Bonus'],
    verified: true,
    source: 'greenhouse'
  },
  {
    title: 'Infrastructure Engineer (AI Platforms)',
    company: 'Galaxy Digital',
    company_type: 'Asset Management',
    location: 'New York, NY',
    type: 'Full-time',
    department: 'Engineering',
    salary_display: '$180,000 - $260,000',
    salary_min: 180000,
    salary_max: 260000,
    salary_currency: 'USD',
    description: 'Build and maintain AI/ML infrastructure for trading and research platforms.',
    requirements: ['5+ years infrastructure engineering', 'Cloud platforms (AWS/GCP)', 'MLOps experience'],
    url: 'https://job-boards.greenhouse.io/galaxydigitalservices/jobs/5812855004',
    posted_date: '2026-03-18',
    tags: ['infrastructure', 'ai', 'mlops', 'cloud'],
    featured: false,
    is_remote: false,
    country: 'United States',
    country_code: 'US',
    city: 'New York',
    seniority: 'Senior',
    work_arrangement: 'Hybrid',
    skills: ['AWS', 'GCP', 'Kubernetes', 'MLOps', 'Infrastructure'],
    benefits: ['401k', 'Health Insurance', 'Equity'],
    verified: true,
    source: 'greenhouse'
  },
  {
    title: 'Compliance Associate/VP',
    company: 'Galaxy Digital',
    company_type: 'Asset Management',
    location: 'New York, NY',
    type: 'Full-time',
    department: 'Legal/Compliance',
    salary_display: '$120,000 - $200,000',
    salary_min: 120000,
    salary_max: 200000,
    salary_currency: 'USD',
    description: 'Support compliance programs across Galaxy\'s regulated businesses.',
    requirements: ['3-7 years compliance experience', 'Financial services background', 'Digital assets knowledge preferred'],
    url: 'https://job-boards.greenhouse.io/galaxydigitalservices/jobs/5764325004',
    posted_date: '2026-03-18',
    tags: ['compliance', 'regulatory', 'legal'],
    featured: false,
    is_remote: false,
    country: 'United States',
    country_code: 'US',
    city: 'New York',
    seniority: 'Mid',
    work_arrangement: 'Hybrid',
    skills: ['Compliance', 'Regulatory', 'AML/KYC', 'Financial Services'],
    benefits: ['401k', 'Health Insurance', 'Equity'],
    verified: true,
    source: 'greenhouse'
  },
  {
    title: 'Vice President of Sales | GK8 by Galaxy',
    company: 'Galaxy Digital',
    company_type: 'Custody',
    location: 'New York, NY',
    type: 'Full-time',
    department: 'Sales',
    salary_display: '$180,000 - $280,000 + Commission',
    salary_min: 180000,
    salary_max: 280000,
    salary_currency: 'USD',
    description: 'Lead enterprise sales for GK8 institutional custody solutions.',
    requirements: ['7+ years enterprise sales', 'Custody/security product experience', 'Institutional relationships'],
    url: 'https://job-boards.greenhouse.io/galaxydigitalservices/jobs/5349190004',
    posted_date: '2026-03-18',
    tags: ['sales', 'enterprise', 'custody', 'b2b'],
    featured: true,
    is_remote: false,
    country: 'United States',
    country_code: 'US',
    city: 'New York',
    seniority: 'Director',
    work_arrangement: 'Hybrid',
    skills: ['Enterprise Sales', 'Custody', 'Institutional Sales', 'Business Development'],
    benefits: ['401k', 'Health Insurance', 'Equity', 'Commission'],
    verified: true,
    source: 'greenhouse'
  },
  {
    title: 'Trading Operations - Derivatives',
    company: 'Galaxy Digital',
    company_type: 'Asset Management',
    location: 'New York, NY',
    type: 'Full-time',
    department: 'Operations',
    salary_display: '$100,000 - $150,000',
    salary_min: 100000,
    salary_max: 150000,
    salary_currency: 'USD',
    description: 'Support derivatives trading operations including trade lifecycle and settlements.',
    requirements: ['2-5 years trading operations', 'Derivatives product knowledge', 'Detail-oriented'],
    url: 'https://job-boards.greenhouse.io/galaxydigitalservices/jobs/5727995004',
    posted_date: '2026-03-18',
    tags: ['operations', 'derivatives', 'trading', 'settlements'],
    featured: false,
    is_remote: false,
    country: 'United States',
    country_code: 'US',
    city: 'New York',
    seniority: 'Mid',
    work_arrangement: 'On-site',
    skills: ['Trading Operations', 'Derivatives', 'Settlements', 'Middle Office'],
    benefits: ['401k', 'Health Insurance', 'Equity'],
    verified: true,
    source: 'greenhouse'
  },
  // Fireblocks Jobs
  {
    title: 'Mobile Engineer (Remote)',
    company: 'Fireblocks',
    company_type: 'Infrastructure',
    location: 'Remote - Americas',
    type: 'Full-time',
    department: 'Engineering',
    salary_display: '$150,000 - $220,000',
    salary_min: 150000,
    salary_max: 220000,
    salary_currency: 'USD',
    description: 'Build mobile applications for Fireblocks enterprise-grade digital asset custody and settlement platform.',
    requirements: ['4+ years mobile development', 'iOS or Android expertise', 'Security-focused development'],
    url: 'https://job-boards.greenhouse.io/fireblocks/jobs/4652122006',
    posted_date: '2026-03-18',
    tags: ['mobile', 'ios', 'android', 'custody', 'security'],
    featured: true,
    is_remote: true,
    country: null,
    country_code: null,
    city: null,
    seniority: 'Mid',
    work_arrangement: 'Remote',
    skills: ['iOS', 'Android', 'Mobile Development', 'Security', 'Crypto'],
    benefits: ['Health Insurance', 'Equity', 'Remote Work'],
    verified: true,
    source: 'greenhouse'
  },
  // Coinbase Jobs (from search results)
  {
    title: 'CaaS Sales Manager',
    company: 'Coinbase',
    company_type: 'Exchange',
    location: 'Remote',
    type: 'Full-time',
    department: 'Sales',
    salary_display: '$140,000 - $200,000 + Bonus',
    salary_min: 140000,
    salary_max: 200000,
    salary_currency: 'USD',
    description: 'Drive sales for Coinbase as a Service (CaaS) products to enterprise clients.',
    requirements: ['5+ years B2B sales', 'Enterprise software experience', 'Fintech/crypto background preferred'],
    url: 'https://www.coinbase.com/careers/positions',
    posted_date: '2026-03-18',
    tags: ['sales', 'enterprise', 'caas', 'b2b'],
    featured: false,
    is_remote: true,
    country: null,
    country_code: null,
    city: null,
    seniority: 'Senior',
    work_arrangement: 'Remote',
    skills: ['Enterprise Sales', 'B2B', 'Account Management', 'Fintech'],
    benefits: ['Health Insurance', 'Equity', 'Remote Work', '401k'],
    verified: true,
    source: 'coinbase'
  },
  {
    title: 'Senior Account Manager - Institutional',
    company: 'Coinbase',
    company_type: 'Exchange',
    location: 'Remote - UK',
    type: 'Full-time',
    department: 'Sales',
    salary_display: '£100,000 - £150,000',
    salary_min: 125000,
    salary_max: 190000,
    salary_currency: 'USD',
    description: 'Manage and grow relationships with institutional clients across EMEA.',
    requirements: ['5+ years institutional sales', 'Financial services experience', 'Crypto markets knowledge'],
    url: 'https://www.coinbase.com/careers/positions',
    posted_date: '2026-03-18',
    tags: ['account management', 'institutional', 'emea', 'sales'],
    featured: true,
    is_remote: true,
    country: 'United Kingdom',
    country_code: 'GB',
    city: 'London',
    seniority: 'Senior',
    work_arrangement: 'Remote',
    skills: ['Institutional Sales', 'Account Management', 'Financial Services', 'Crypto'],
    benefits: ['Health Insurance', 'Equity', 'Remote Work'],
    verified: true,
    source: 'coinbase'
  },
  {
    title: 'Compliance Lead Analyst',
    company: 'Coinbase',
    company_type: 'Exchange',
    location: 'Remote',
    type: 'Full-time',
    department: 'Compliance',
    salary_display: '$120,000 - $170,000',
    salary_min: 120000,
    salary_max: 170000,
    salary_currency: 'USD',
    description: 'Lead compliance analysis and regulatory monitoring for Coinbase operations.',
    requirements: ['5+ years compliance experience', 'AML/BSA expertise', 'Crypto regulatory knowledge'],
    url: 'https://www.coinbase.com/careers/positions',
    posted_date: '2026-03-18',
    tags: ['compliance', 'regulatory', 'aml', 'analyst'],
    featured: false,
    is_remote: true,
    country: null,
    country_code: null,
    city: null,
    seniority: 'Senior',
    work_arrangement: 'Remote',
    skills: ['Compliance', 'AML/KYC', 'Regulatory', 'Risk Analysis'],
    benefits: ['Health Insurance', 'Equity', 'Remote Work', '401k'],
    verified: true,
    source: 'coinbase'
  },
  {
    title: 'Data Analytics Engineer',
    company: 'Coinbase',
    company_type: 'Exchange',
    location: 'Remote',
    type: 'Full-time',
    department: 'Data',
    salary_display: '$150,000 - $210,000',
    salary_min: 150000,
    salary_max: 210000,
    salary_currency: 'USD',
    description: 'Build data pipelines and analytics infrastructure for Coinbase products.',
    requirements: ['4+ years data engineering', 'SQL, Python proficiency', 'Cloud data platforms'],
    url: 'https://www.coinbase.com/careers/positions',
    posted_date: '2026-03-18',
    tags: ['data', 'analytics', 'engineering', 'etl'],
    featured: false,
    is_remote: true,
    country: null,
    country_code: null,
    city: null,
    seniority: 'Mid',
    work_arrangement: 'Remote',
    skills: ['SQL', 'Python', 'Data Engineering', 'ETL', 'Cloud'],
    benefits: ['Health Insurance', 'Equity', 'Remote Work', '401k'],
    verified: true,
    source: 'coinbase'
  },
  // Kraken Jobs (from search)
  {
    title: 'Managing Director Europe',
    company: 'Kraken',
    company_type: 'Exchange',
    location: 'Remote - Europe/UK',
    type: 'Full-time',
    department: 'Operations',
    salary_display: '€200,000 - €350,000',
    salary_min: 215000,
    salary_max: 380000,
    salary_currency: 'USD',
    description: 'Lead Kraken\'s European operations and business development.',
    requirements: ['10+ years financial services leadership', 'European regulatory experience', 'Crypto industry background'],
    url: 'https://www.kraken.com/careers',
    posted_date: '2026-03-18',
    tags: ['leadership', 'europe', 'operations', 'executive'],
    featured: true,
    is_remote: true,
    country: null,
    country_code: null,
    city: null,
    seniority: 'Director',
    work_arrangement: 'Remote',
    skills: ['Leadership', 'Operations', 'Business Development', 'Regulatory'],
    benefits: ['Health Insurance', 'Equity', 'Remote Work', 'Competitive Salary'],
    verified: true,
    source: 'kraken'
  },
  {
    title: 'Product Manager, Trading',
    company: 'Kraken',
    company_type: 'Exchange',
    location: 'Remote',
    type: 'Full-time',
    department: 'Product',
    salary_display: '$150,000 - $220,000',
    salary_min: 150000,
    salary_max: 220000,
    salary_currency: 'USD',
    description: 'Own product strategy and roadmap for Kraken\'s trading products.',
    requirements: ['5+ years product management', 'Trading platform experience', 'Crypto markets knowledge'],
    url: 'https://www.kraken.com/careers',
    posted_date: '2026-03-18',
    tags: ['product', 'trading', 'strategy', 'roadmap'],
    featured: false,
    is_remote: true,
    country: null,
    country_code: null,
    city: null,
    seniority: 'Senior',
    work_arrangement: 'Remote',
    skills: ['Product Management', 'Trading', 'Crypto', 'Strategy'],
    benefits: ['Health Insurance', 'Equity', 'Remote Work'],
    verified: true,
    source: 'kraken'
  },
  {
    title: 'Institutional Sales Representative - Staked',
    company: 'Kraken',
    company_type: 'Exchange',
    location: 'Remote',
    type: 'Full-time',
    department: 'Sales',
    salary_display: '$120,000 - $180,000 + Commission',
    salary_min: 120000,
    salary_max: 180000,
    salary_currency: 'USD',
    description: 'Drive institutional sales for Kraken\'s staking products.',
    requirements: ['3+ years institutional sales', 'Staking/DeFi knowledge', 'Financial services background'],
    url: 'https://www.kraken.com/careers',
    posted_date: '2026-03-18',
    tags: ['sales', 'institutional', 'staking', 'defi'],
    featured: false,
    is_remote: true,
    country: null,
    country_code: null,
    city: null,
    seniority: 'Mid',
    work_arrangement: 'Remote',
    skills: ['Institutional Sales', 'Staking', 'DeFi', 'Business Development'],
    benefits: ['Health Insurance', 'Equity', 'Remote Work', 'Commission'],
    verified: true,
    source: 'kraken'
  },
  // Galaxy Digital London/Europe roles
  {
    title: 'VP, Strategy & Corporate Development',
    company: 'Galaxy Digital',
    company_type: 'Asset Management',
    location: 'London, UK',
    type: 'Full-time',
    department: 'Corporate',
    salary_display: '£150,000 - £220,000',
    salary_min: 190000,
    salary_max: 280000,
    salary_currency: 'USD',
    description: 'Lead strategic initiatives and M&A activity for Galaxy\'s European operations.',
    requirements: ['7+ years strategy/corp dev', 'M&A experience', 'Financial services background'],
    url: 'https://job-boards.greenhouse.io/galaxydigitalservices/jobs/5695082004',
    posted_date: '2026-03-18',
    tags: ['strategy', 'corporate development', 'ma', 'finance'],
    featured: false,
    is_remote: false,
    country: 'United Kingdom',
    country_code: 'GB',
    city: 'London',
    seniority: 'Senior',
    work_arrangement: 'On-site',
    skills: ['Strategy', 'M&A', 'Corporate Development', 'Financial Analysis'],
    benefits: ['Health Insurance', 'Equity', 'Pension'],
    verified: true,
    source: 'greenhouse'
  },
  {
    title: 'Director, Algo Trading/SOR Developer',
    company: 'Galaxy Digital',
    company_type: 'Asset Management',
    location: 'London, UK',
    type: 'Full-time',
    department: 'Engineering',
    salary_display: '£180,000 - £280,000',
    salary_min: 230000,
    salary_max: 360000,
    salary_currency: 'USD',
    description: 'Build algorithmic trading and smart order routing systems for digital asset markets.',
    requirements: ['10+ years algo trading development', 'SOR experience', 'Low-latency systems'],
    url: 'https://job-boards.greenhouse.io/galaxydigitalservices/jobs/5560698004',
    posted_date: '2026-03-18',
    tags: ['algo trading', 'sor', 'engineering', 'quantitative'],
    featured: true,
    is_remote: false,
    country: 'United Kingdom',
    country_code: 'GB',
    city: 'London',
    seniority: 'Director',
    work_arrangement: 'On-site',
    skills: ['Algo Trading', 'Smart Order Routing', 'Low Latency', 'Python', 'C++'],
    benefits: ['Health Insurance', 'Equity', 'Pension', 'Performance Bonus'],
    verified: true,
    source: 'greenhouse'
  },
  // Galaxy Digital APAC roles
  {
    title: 'Vice President, Compliance (APAC)',
    company: 'Galaxy Digital',
    company_type: 'Asset Management',
    location: 'Hong Kong',
    type: 'Full-time',
    department: 'Legal/Compliance',
    salary_display: 'HKD 1,500,000 - 2,500,000',
    salary_min: 190000,
    salary_max: 320000,
    salary_currency: 'USD',
    description: 'Lead compliance programs across Galaxy\'s APAC operations.',
    requirements: ['7+ years compliance', 'APAC regulatory experience', 'Digital assets knowledge'],
    url: 'https://job-boards.greenhouse.io/galaxydigitalservices/jobs/5729578004',
    posted_date: '2026-03-18',
    tags: ['compliance', 'apac', 'regulatory', 'hong kong'],
    featured: false,
    is_remote: false,
    country: 'Hong Kong',
    country_code: 'HK',
    city: 'Hong Kong',
    seniority: 'Senior',
    work_arrangement: 'On-site',
    skills: ['Compliance', 'APAC Regulations', 'AML/KYC', 'Digital Assets'],
    benefits: ['Health Insurance', 'Equity', 'MPF'],
    verified: true,
    source: 'greenhouse'
  },
  {
    title: 'Vice President/Director, Exotic Derivatives Trader',
    company: 'Galaxy Digital',
    company_type: 'Asset Management',
    location: 'Hong Kong',
    type: 'Full-time',
    department: 'Trading',
    salary_display: 'HKD 2,000,000 - 4,000,000',
    salary_min: 250000,
    salary_max: 510000,
    salary_currency: 'USD',
    description: 'Trade exotic derivatives on digital assets for institutional clients.',
    requirements: ['7+ years derivatives trading', 'Exotic products experience', 'Crypto markets knowledge'],
    url: 'https://job-boards.greenhouse.io/galaxydigitalservices/jobs/5821744004',
    posted_date: '2026-03-18',
    tags: ['trading', 'derivatives', 'exotic', 'crypto'],
    featured: true,
    is_remote: false,
    country: 'Hong Kong',
    country_code: 'HK',
    city: 'Hong Kong',
    seniority: 'Director',
    work_arrangement: 'On-site',
    skills: ['Derivatives Trading', 'Exotic Options', 'Risk Management', 'Crypto'],
    benefits: ['Health Insurance', 'Equity', 'MPF', 'Performance Bonus'],
    verified: true,
    source: 'greenhouse'
  },
  // Galaxy Digital internships
  {
    title: '2026 Finance Internship',
    company: 'Galaxy Digital',
    company_type: 'Asset Management',
    location: 'New York, NY',
    type: 'Internship',
    department: 'Finance',
    salary_display: '$85,000 - $95,000 annualized',
    salary_min: 85000,
    salary_max: 95000,
    salary_currency: 'USD',
    description: 'Summer internship in Galaxy\'s Finance team. Gain exposure to digital asset financial operations.',
    requirements: ['Pursuing degree in Finance/Accounting', 'Strong analytical skills', 'Interest in digital assets'],
    url: 'https://job-boards.greenhouse.io/galaxydigitalservices/jobs/5693193004',
    posted_date: '2026-03-18',
    tags: ['internship', 'finance', 'summer', 'early career'],
    featured: false,
    is_remote: false,
    country: 'United States',
    country_code: 'US',
    city: 'New York',
    seniority: 'Junior',
    work_arrangement: 'On-site',
    skills: ['Financial Analysis', 'Excel', 'Accounting'],
    benefits: ['Competitive Stipend', 'Networking Opportunities'],
    verified: true,
    source: 'greenhouse'
  },
  {
    title: '2026 Sales and Trading Internship',
    company: 'Galaxy Digital',
    company_type: 'Asset Management',
    location: 'New York, NY',
    type: 'Internship',
    department: 'Sales',
    salary_display: '$85,000 - $95,000 annualized',
    salary_min: 85000,
    salary_max: 95000,
    salary_currency: 'USD',
    description: 'Summer internship on Galaxy\'s Sales & Trading desk. Learn digital asset markets firsthand.',
    requirements: ['Pursuing degree in Finance/Business', 'Interest in trading', 'Strong communication skills'],
    url: 'https://job-boards.greenhouse.io/galaxydigitalservices/jobs/5693202004',
    posted_date: '2026-03-18',
    tags: ['internship', 'sales', 'trading', 'early career'],
    featured: false,
    is_remote: false,
    country: 'United States',
    country_code: 'US',
    city: 'New York',
    seniority: 'Junior',
    work_arrangement: 'On-site',
    skills: ['Sales', 'Trading', 'Communication', 'Financial Markets'],
    benefits: ['Competitive Stipend', 'Networking Opportunities'],
    verified: true,
    source: 'greenhouse'
  }
]

async function main() {
  console.log(`Adding ${newJobs.length} new jobs to Supabase...`)
  
  // First check for existing jobs by URL to avoid duplicates
  const urls = newJobs.map(j => j.url)
  const { data: existing } = await supabase
    .from('jobs')
    .select('url')
    .in('url', urls)
  
  const existingUrls = new Set((existing || []).map(j => j.url))
  const jobsToAdd = newJobs.filter(j => !existingUrls.has(j.url))
  
  console.log(`Found ${existingUrls.size} existing jobs, adding ${jobsToAdd.length} new ones`)
  
  if (jobsToAdd.length === 0) {
    console.log('No new jobs to add')
    return { added: 0 }
  }
  
  const { data, error } = await supabase
    .from('jobs')
    .insert(jobsToAdd)
    .select('id, title, company')
  
  if (error) {
    console.error('Error inserting jobs:', error)
    throw error
  }
  
  console.log(`Successfully added ${data?.length || 0} jobs:`)
  data?.forEach(job => {
    console.log(`  - ${job.title} at ${job.company}`)
  })
  
  return { added: data?.length || 0 }
}

main()
  .then(result => {
    console.log(`\nDone! Added ${result.added} jobs.`)
    process.exit(0)
  })
  .catch(err => {
    console.error('Failed:', err)
    process.exit(1)
  })
