const fs = require('fs');
const path = require('path');

const jobsPath = path.join(__dirname, '..', 'data', 'jobs.json');
const data = JSON.parse(fs.readFileSync(jobsPath, 'utf8'));

const newJobs = [
  {
    "title": "Finance Systems Analyst",
    "company": "Chainalysis",
    "company_type": "Analytics",
    "location": "Remote - USA",
    "type": "Full-time",
    "department": "Finance",
    "salary_display": "$100,000 - $140,000",
    "url": "https://www.chainalysis.com/careers/job-openings/",
    "seniority": "Mid",
    "work_arrangement": "Remote",
    "skills": ["Finance Systems", "ERP", "Data Analysis", "Accounting"],
    "verified": true,
    "verifiedAt": "2026-03-29T21:00:00Z",
    "source": "chainalysis",
    "postedDate": "2026-03-29",
    "tags": ["finance", "systems", "analyst"],
    "featured": false,
    "isRemote": true
  },
  {
    "title": "Director, Communications and Content",
    "company": "Chainalysis",
    "company_type": "Analytics",
    "location": "New York, NY",
    "type": "Full-time",
    "department": "Marketing",
    "salary_display": "$180,000 - $250,000",
    "url": "https://www.chainalysis.com/careers/job-openings/",
    "seniority": "Director",
    "work_arrangement": "Hybrid",
    "skills": ["Communications", "Content Strategy", "PR", "Leadership"],
    "verified": true,
    "verifiedAt": "2026-03-29T21:00:00Z",
    "source": "chainalysis",
    "postedDate": "2026-03-29",
    "tags": ["marketing", "communications", "director"],
    "featured": true,
    "isRemote": false
  },
  {
    "title": "Applied AI Engineer",
    "company": "Chainalysis",
    "company_type": "Analytics",
    "location": "Aarhus, Denmark",
    "type": "Full-time",
    "department": "Engineering",
    "salary_display": null,
    "url": "https://www.chainalysis.com/careers/job-openings/",
    "seniority": "Mid",
    "work_arrangement": "Hybrid",
    "skills": ["AI/ML", "Python", "Machine Learning", "NLP"],
    "verified": true,
    "verifiedAt": "2026-03-29T21:00:00Z",
    "source": "chainalysis",
    "postedDate": "2026-03-29",
    "tags": ["ai", "engineering", "machine-learning"],
    "featured": true,
    "isRemote": false
  },
  {
    "title": "Business Development Representative",
    "company": "Chainalysis",
    "company_type": "Analytics",
    "location": "Remote",
    "type": "Full-time",
    "department": "Sales",
    "salary_display": "$60,000 - $80,000 + Commission",
    "url": "https://www.chainalysis.com/careers/job-openings/",
    "seniority": "Junior",
    "work_arrangement": "Remote",
    "skills": ["Sales", "Outbound", "Prospecting", "CRM"],
    "verified": true,
    "verifiedAt": "2026-03-29T21:00:00Z",
    "source": "chainalysis",
    "postedDate": "2026-03-29",
    "tags": ["sales", "bdr", "entry-level"],
    "featured": false,
    "isRemote": true
  },
  {
    "title": "Staff Full Stack Engineer",
    "company": "Fireblocks",
    "company_type": "Infrastructure",
    "location": "New York, NY",
    "type": "Full-time",
    "department": "Engineering",
    "salary_display": "$177,000 - $230,000",
    "url": "https://www.fireblocks.com/careers",
    "seniority": "Senior",
    "work_arrangement": "Hybrid",
    "skills": ["Full Stack", "React", "Node.js", "TypeScript", "Security"],
    "verified": true,
    "verifiedAt": "2026-03-29T21:00:00Z",
    "source": "fireblocks",
    "postedDate": "2026-03-29",
    "tags": ["engineering", "fullstack", "staff"],
    "featured": true,
    "isRemote": false
  },
  {
    "title": "Senior C++ Engineer",
    "company": "Fireblocks",
    "company_type": "Infrastructure",
    "location": "Tel Aviv, Israel",
    "type": "Full-time",
    "department": "Engineering",
    "salary_display": null,
    "url": "https://www.fireblocks.com/careers",
    "seniority": "Senior",
    "work_arrangement": "Hybrid",
    "skills": ["C++", "Low-Level Programming", "Cryptography", "Security"],
    "verified": true,
    "verifiedAt": "2026-03-29T21:00:00Z",
    "source": "fireblocks",
    "postedDate": "2026-03-29",
    "tags": ["engineering", "cpp", "security"],
    "featured": false,
    "isRemote": false
  },
  {
    "title": "Application Security Engineer",
    "company": "Fireblocks",
    "company_type": "Infrastructure",
    "location": "Tel Aviv, Israel",
    "type": "Full-time",
    "department": "Security",
    "salary_display": null,
    "url": "https://www.fireblocks.com/careers",
    "seniority": "Senior",
    "work_arrangement": "Hybrid",
    "skills": ["Application Security", "Penetration Testing", "Security Audits", "DevSecOps"],
    "verified": true,
    "verifiedAt": "2026-03-29T21:00:00Z",
    "source": "fireblocks",
    "postedDate": "2026-03-29",
    "tags": ["security", "appsec", "engineering"],
    "featured": false,
    "isRemote": false
  },
  {
    "title": "Technical Integration Engineer",
    "company": "Fireblocks",
    "company_type": "Infrastructure",
    "location": "Boston, MA",
    "type": "Full-time",
    "department": "Engineering",
    "salary_display": "$130,000 - $180,000",
    "url": "https://www.fireblocks.com/careers",
    "seniority": "Mid",
    "work_arrangement": "Hybrid",
    "skills": ["API Integration", "Technical Support", "Client Onboarding", "Blockchain"],
    "verified": true,
    "verifiedAt": "2026-03-29T21:00:00Z",
    "source": "fireblocks",
    "postedDate": "2026-03-29",
    "tags": ["integration", "technical", "client-facing"],
    "featured": false,
    "isRemote": false
  },
  {
    "title": "Principal Product Manager, AI Platform",
    "company": "Circle",
    "company_type": "Stablecoin",
    "location": "Remote",
    "type": "Full-time",
    "department": "Product",
    "salary_display": "$185,000 - $260,000",
    "url": "https://careers.circle.com/us/en/c/product-jobs",
    "seniority": "Senior",
    "work_arrangement": "Remote",
    "skills": ["Product Management", "AI/ML", "Platform", "Strategy"],
    "verified": true,
    "verifiedAt": "2026-03-29T21:00:00Z",
    "source": "circle",
    "postedDate": "2026-03-29",
    "tags": ["product", "ai", "principal"],
    "featured": true,
    "isRemote": true
  },
  {
    "title": "VP, Growth Marketing",
    "company": "Circle",
    "company_type": "Stablecoin",
    "location": "Remote",
    "type": "Full-time",
    "department": "Marketing",
    "salary_display": "$220,000 - $300,000",
    "url": "https://careers.circle.com/us/en/c/marketing-jobs",
    "seniority": "Director",
    "work_arrangement": "Remote",
    "skills": ["Growth Marketing", "Leadership", "Digital Marketing", "Analytics"],
    "verified": true,
    "verifiedAt": "2026-03-29T21:00:00Z",
    "source": "circle",
    "postedDate": "2026-03-29",
    "tags": ["marketing", "growth", "vp"],
    "featured": true,
    "isRemote": true
  },
  {
    "title": "Senior Manager, Global Risk Management",
    "company": "Circle",
    "company_type": "Stablecoin",
    "location": "Remote",
    "type": "Full-time",
    "department": "Risk",
    "salary_display": "$150,000 - $200,000",
    "url": "https://careers.circle.com/us/en",
    "seniority": "Senior",
    "work_arrangement": "Remote",
    "skills": ["Risk Management", "Compliance", "Financial Risk", "Strategy"],
    "verified": true,
    "verifiedAt": "2026-03-29T21:00:00Z",
    "source": "circle",
    "postedDate": "2026-03-29",
    "tags": ["risk", "compliance", "management"],
    "featured": false,
    "isRemote": true
  },
  {
    "title": "Senior Machine Learning Platform Engineer",
    "company": "Coinbase",
    "company_type": "Exchange",
    "location": "Remote",
    "type": "Full-time",
    "department": "Engineering",
    "salary_display": "$180,000 - $250,000",
    "url": "https://www.coinbase.com/careers/positions",
    "seniority": "Senior",
    "work_arrangement": "Remote",
    "skills": ["ML Infrastructure", "Python", "Kubernetes", "MLOps"],
    "verified": true,
    "verifiedAt": "2026-03-29T21:00:00Z",
    "source": "coinbase",
    "postedDate": "2026-03-29",
    "tags": ["ml", "platform", "engineering"],
    "featured": true,
    "isRemote": true
  },
  {
    "title": "Base Senior Product Manager, Privacy",
    "company": "Coinbase",
    "company_type": "Exchange",
    "location": "Remote",
    "type": "Full-time",
    "department": "Product",
    "salary_display": "$175,000 - $240,000",
    "url": "https://www.coinbase.com/careers/positions",
    "seniority": "Senior",
    "work_arrangement": "Remote",
    "skills": ["Product Management", "Privacy", "Base", "L2", "Web3"],
    "verified": true,
    "verifiedAt": "2026-03-29T21:00:00Z",
    "source": "coinbase",
    "postedDate": "2026-03-29",
    "tags": ["product", "base", "privacy"],
    "featured": true,
    "isRemote": true
  },
  {
    "title": "Junior Digital Marketing Specialist",
    "company": "Kraken",
    "company_type": "Exchange",
    "location": "Remote",
    "type": "Full-time",
    "department": "Marketing",
    "salary_display": "$65,000 - $90,000",
    "url": "https://www.kraken.com/careers",
    "seniority": "Junior",
    "work_arrangement": "Remote",
    "skills": ["Digital Marketing", "Social Media", "Content", "Analytics"],
    "verified": true,
    "verifiedAt": "2026-03-29T21:00:00Z",
    "source": "kraken",
    "postedDate": "2026-03-29",
    "tags": ["marketing", "digital", "entry-level"],
    "featured": false,
    "isRemote": true
  },
  {
    "title": "OTC Junior Trader - Derivatives",
    "company": "Kraken",
    "company_type": "Exchange",
    "location": "Remote - APAC",
    "type": "Full-time",
    "department": "Trading",
    "salary_display": "$96,000 - $150,000",
    "url": "https://www.kraken.com/careers",
    "seniority": "Junior",
    "work_arrangement": "Remote",
    "skills": ["OTC Trading", "Derivatives", "Crypto", "Risk Management"],
    "verified": true,
    "verifiedAt": "2026-03-29T21:00:00Z",
    "source": "kraken",
    "postedDate": "2026-03-29",
    "tags": ["trading", "otc", "derivatives"],
    "featured": true,
    "isRemote": true
  },
  {
    "title": "Smart Contract Auditor",
    "company": "Kraken",
    "company_type": "Exchange",
    "location": "Remote",
    "type": "Full-time",
    "department": "Security",
    "salary_display": "$150,000 - $220,000",
    "url": "https://www.kraken.com/careers",
    "seniority": "Senior",
    "work_arrangement": "Remote",
    "skills": ["Smart Contracts", "Solidity", "Security Auditing", "DeFi"],
    "verified": true,
    "verifiedAt": "2026-03-29T21:00:00Z",
    "source": "kraken",
    "postedDate": "2026-03-29",
    "tags": ["security", "smart-contracts", "audit"],
    "featured": true,
    "isRemote": true
  },
  {
    "title": "Product Lead, Financial Infrastructure",
    "company": "Anchorage Digital",
    "company_type": "Custody",
    "location": "Remote - USA",
    "type": "Full-time",
    "department": "Product",
    "salary_display": "$180,000 - $250,000",
    "url": "https://www.anchorage.com/careers",
    "seniority": "Senior",
    "work_arrangement": "Remote",
    "skills": ["Product Management", "Financial Infrastructure", "Banking", "Strategy"],
    "verified": true,
    "verifiedAt": "2026-03-29T21:00:00Z",
    "source": "anchorage",
    "postedDate": "2026-03-29",
    "tags": ["product", "fininfra", "leadership"],
    "featured": true,
    "isRemote": true
  },
  {
    "title": "Blockchain Researcher",
    "company": "Anchorage Digital",
    "company_type": "Custody",
    "location": "Remote - USA",
    "type": "Full-time",
    "department": "Research",
    "salary_display": "$140,000 - $200,000",
    "url": "https://www.anchorage.com/careers",
    "seniority": "Mid",
    "work_arrangement": "Remote",
    "skills": ["Blockchain Research", "Protocol Analysis", "DeFi", "Web3"],
    "verified": true,
    "verifiedAt": "2026-03-29T21:00:00Z",
    "source": "anchorage",
    "postedDate": "2026-03-29",
    "tags": ["research", "blockchain", "protocol"],
    "featured": false,
    "isRemote": true
  },
  {
    "title": "Application Security Engineer",
    "company": "Paxos",
    "company_type": "Stablecoin",
    "location": "Remote",
    "type": "Full-time",
    "department": "Security",
    "salary_display": "$160,000 - $220,000",
    "url": "https://www.paxos.com/careers",
    "seniority": "Senior",
    "work_arrangement": "Remote",
    "skills": ["Application Security", "Penetration Testing", "Security", "DevSecOps"],
    "verified": true,
    "verifiedAt": "2026-03-29T21:00:00Z",
    "source": "paxos",
    "postedDate": "2026-03-29",
    "tags": ["security", "appsec", "engineering"],
    "featured": false,
    "isRemote": true
  },
  {
    "title": "Head of Financial Crimes Compliance",
    "company": "Paxos",
    "company_type": "Stablecoin",
    "location": "New York, NY",
    "type": "Full-time",
    "department": "Compliance",
    "salary_display": "$200,000 - $280,000",
    "url": "https://www.paxos.com/careers",
    "seniority": "Director",
    "work_arrangement": "Hybrid",
    "skills": ["Financial Crimes", "AML", "BSA", "Compliance Leadership"],
    "verified": true,
    "verifiedAt": "2026-03-29T21:00:00Z",
    "source": "paxos",
    "postedDate": "2026-03-29",
    "tags": ["compliance", "aml", "leadership"],
    "featured": true,
    "isRemote": false
  },
  {
    "title": "Events Marketing Lead",
    "company": "Paxos",
    "company_type": "Stablecoin",
    "location": "New York, NY",
    "type": "Full-time",
    "department": "Marketing",
    "salary_display": "$120,000 - $160,000",
    "url": "https://www.paxos.com/careers",
    "seniority": "Mid",
    "work_arrangement": "Hybrid",
    "skills": ["Event Marketing", "Conference Planning", "Marketing", "Partnerships"],
    "verified": true,
    "verifiedAt": "2026-03-29T21:00:00Z",
    "source": "paxos",
    "postedDate": "2026-03-29",
    "tags": ["marketing", "events", "conferences"],
    "featured": false,
    "isRemote": false
  }
];

// Check for duplicates and add new jobs
const existingTitles = new Set(data.jobs.map(j => `${j.company.toLowerCase()}-${j.title.toLowerCase()}`));
let added = 0;

for (const job of newJobs) {
  const key = `${job.company.toLowerCase()}-${job.title.toLowerCase()}`;
  if (!existingTitles.has(key)) {
    data.jobs.push(job);
    existingTitles.add(key);
    added++;
    console.log(`Added: ${job.title} at ${job.company}`);
  } else {
    console.log(`Skipped (duplicate): ${job.title} at ${job.company}`);
  }
}

// Update scrape date
data.scraped_date = new Date().toISOString();

// Write back
fs.writeFileSync(jobsPath, JSON.stringify(data, null, 2));

console.log(`\nTotal added: ${added}`);
console.log(`Total jobs in database: ${data.jobs.length}`);
